map_update_interval: 1.0
maxUrange: 5.0
sigma: 0.1
kernelSize: 1
lstep: 0.15
astep: 0.15
iterations: 1
lsigma: 0.1
ogain: 3.0
lskip: 0
srr: 0.1
srt: 0.2
str: 0.1
stt: 0.2
linearUpdate: 1.0
angularUpdate: 0.5
temporalUpdate: 0.4
resampleThreshold: 0.5
particles: 10
xmin: -5.0
ymin: -4.0
xmax: 5.0
ymax: 5.0
delta: 0.02
llsamplerange: 0.01
llsamplestep: 0.05
lasamplerange: 0.005
lasamplestep: 0.005
